exports.decks = [
  // --------------- HIRAGANA --------------------------
  { character: "あ", translation: "A", type: "hiragana" },
  { character: "い", translation: "I", type: "hiragana" },
  { character: "う", translation: "U", type: "hiragana" },
  { character: "え", translation: "E", type: "hiragana" },
  { character: "お", translation: "O", type: "hiragana" },
  { character: "か", translation: "KA", type: "hiragana" },
  { character: "き", translation: "KI", type: "hiragana" },
  { character: "く", translation: "KU", type: "hiragana" },
  { character: "け", translation: "KE", type: "hiragana" },
  { character: "こ", translation: "KO", type: "hiragana" },
  { character: "さ", translation: "SA", type: "hiragana" },
  { character: "し", translation: "SHI", type: "hiragana" },
  { character: "す", translation: "SU", type: "hiragana" },
  { character: "せ", translation: "SE", type: "hiragana" },
  { character: "そ", translation: "SO", type: "hiragana" },
  { character: "た", translation: "TA", type: "hiragana" },
  { character: "ち", translation: "CHI", type: "hiragana" },
  { character: "つ", translation: "TSU", type: "hiragana" },
  { character: "て", translation: "TE", type: "hiragana" },
  { character: "と", translation: "TO", type: "hiragana" },
  { character: "な", translation: "NA", type: "hiragana" },
  { character: "に", translation: "NI", type: "hiragana" },
  { character: "ぬ", translation: "NU", type: "hiragana" },
  { character: "ね", translation: "NE", type: "hiragana" },
  { character: "の", translation: "NO", type: "hiragana" },
  { character: "は", translation: "HA", type: "hiragana" },
  { character: "ひ", translation: "HI", type: "hiragana" },
  { character: "ふ", translation: "FU", type: "hiragana" },
  { character: "へ", translation: "HE", type: "hiragana" },
  { character: "ほ", translation: "HO", type: "hiragana" },
  { character: "ま", translation: "MA", type: "hiragana" },
  { character: "み", translation: "MI", type: "hiragana" },
  { character: "む", translation: "MU", type: "hiragana" },
  { character: "め", translation: "ME", type: "hiragana" },
  { character: "も", translation: "MO", type: "hiragana" },
  { character: "や", translation: "YA", type: "hiragana" },
  { character: "ゆ", translation: "YU", type: "hiragana" },
  { character: "よ", translation: "YO", type: "hiragana" },
  { character: "ら", translation: "RA", type: "hiragana" },
  { character: "り", translation: "RI", type: "hiragana" },
  { character: "る", translation: "RU", type: "hiragana" },
  { character: "れ", translation: "RE", type: "hiragana" },
  { character: "ろ", translation: "RO", type: "hiragana" },
  { character: "わ", translation: "WA", type: "hiragana" },
  { character: "を", translation: "O", type: "hiragana" },
  { character: "ん", translation: "N", type: "hiragana" },

  // ------------------KATAKANA -----------------------
  { character: "ア", translation: "A", type: "katakana" },
  { character: "イ", translation: "I", type: "katakana" },
  { character: "ウ", translation: "U", type: "katakana" },
  { character: "エ", translation: "E", type: "katakana" },
  { character: "オ", translation: "O", type: "katakana" },
  { character: "カ", translation: "KA", type: "katakana" },
  { character: "キ", translation: "KI", type: "katakana" },
  { character: "ク", translation: "KU", type: "katakana" },
  { character: "ケ", translation: "KE", type: "katakana" },
  { character: "コ", translation: "KO", type: "katakana" },
  { character: "サ", translation: "SA", type: "katakana" },
  { character: "シ", translation: "SHI", type: "katakana" },
  { character: "ス", translation: "SU", type: "katakana" },
  { character: "セ", translation: "SE", type: "katakana" },
  { character: "ソ", translation: "SO", type: "katakana" },
  { character: "タ", translation: "TA", type: "katakana" },
  { character: "チ", translation: "CHI", type: "katakana" },
  { character: "ツ", translation: "TSU", type: "katakana" },
  { character: "テ", translation: "TE", type: "katakana" },
  { character: "ト", translation: "TO", type: "katakana" },
  { character: "ナ", translation: "NA", type: "katakana" },
  { character: "ニ", translation: "NI", type: "katakana" },
  { character: "ヌ", translation: "NU", type: "katakana" },
  { character: "ネ", translation: "NE", type: "katakana" },
  { character: "ノ", translation: "NO", type: "katakana" },
  { character: "ハ", translation: "HA", type: "katakana" },
  { character: "ヒ", translation: "HI", type: "katakana" },
  { character: "フ", translation: "FU", type: "katakana" },
  { character: "ヘ", translation: "HE", type: "katakana" },
  { character: "ホ", translation: "HO", type: "katakana" },
  { character: "マ", translation: "MA", type: "katakana" },
  { character: "ミ", translation: "MI", type: "katakana" },
  { character: "ム", translation: "MU", type: "katakana" },
  { character: "メ", translation: "ME", type: "katakana" },
  { character: "モ", translation: "MO", type: "katakana" },
  { character: "ヤ", translation: "YA", type: "katakana" },
  { character: "ユ", translation: "YU", type: "katakana" },
  { character: "ヨ", translation: "YO", type: "katakana" },
  { character: "ラ", translation: "RA", type: "katakana" },
  { character: "リ", translation: "RI", type: "katakana" },
  { character: "ル", translation: "RU", type: "katakana" },
  { character: "レ", translation: "RE", type: "katakana" },
  { character: "ロ", translation: "RO", type: "katakana" },
  { character: "ワ", translation: "WA", type: "katakana" },
  { character: "ヲ", translation: "O", type: "katakana" },
  { character: "ン", translation: "N", type: "katakana" },

  // ---------------- ADJECTIVES -----------------------
  { character: "おおき", translation: "big", type: "adjective" },
  { character: "ちいさい", translation: "small", type: "adjective" },
  { character: "たかい", translation: "expensive", type: "adjective" },
  { character: "やさい", translation: "cheap", type: "adjective" },
  { character: "あたらしい", translation: "new", type: "adjective" },
  { character: "ふるい", translation: "old", type: "adjective" },
  { character: "いい", translation: "good", type: "adjective" },
  { character: "わるい", translation: "bad", type: "adjective" },
  { character: "むずかしい", translation: "difficult", type: "adjective" },
  { character: "かんたん", translation: "easy", type: "adjective" },
  { character: "やさしい", translation: "kind/gentle", type: "adjective" },
  { character: "とおい", translation: "far", type: "adjective" },
  { character: "ちかい", translation: "near", type: "adjective" },
  { character: "おいしい", translation: "delicious", type: "adjective" },
  { character: "まずい", translation: "disgusting", type: "adjective" },
  { character: "いそがしい", translation: "busy", type: "adjective" },
  { character: "きれい", translation: "beautiful/clean", type: "adjective" },
  { character: "しつれい", translation: "rude/impolite", type: "adjective" },
  { character: "ゆうめい", translation: "famous", type: "adjective" },
  { character: "ていねい", translation: "polite", type: "adjective" },
  { character: "すき", translation: "like", type: "adjective" },
  { character: "きらい", translation: "dislike", type: "adjective" },
  { character: "しずか", translation: "quiet", type: "adjective" },
  { character: "さむい", translation: "cold", type: "adjective" },
  { character: "ひま", translation: "free (not busy)", type: "adjective" },
  { character: "にぎやか", translation: "lively", type: "adjective" },
  { character: "べんり", translation: "convenient, useful", type: "adjective" },
  { character: "ふべん", translation: "inconvenient", type: "adjective" },
  { character: "げんき", translation: "healthy", type: "adjective" },
  { character: "いろいろ", translation: "variety", type: "adjective" },
  { character: "おもしろい", translation: "interesting", type: "adjective" },

  // ------------------ VERBS --------------------------
  { character: "みる", translation: "Watch,see,look", type: "verb" },
  { character: "きく", translation: "listen, hear, ask", type: "verb" },
  { character: "たべる", translation: "to eat", type: "verb" },
  { character: "のむ", translation: "to drink", type: "verb" },
  { character: "よむ", translation: "to read", type: "verb" },
  { character: "かく", translation: "to write", type: "verb" },
  { character: "はなす", translation: "to speak", type: "verb" },
  { character: "うたう", translation: "to sing", type: "verb" },
  { character: "ねる", translation: "to sleep", type: "verb" },
  { character: "おきる", translation: "to wake up", type: "verb" },
  { character: "あう", translation: "to meet up", type: "verb" },
  { character: "かう", translation: "to buy", type: "verb" },
  { character: "かえる", translation: "to return", type: "verb" },
  { character: "いく", translation: "to go", type: "verb" },
  { character: "きる", translation: "to come", type: "verb" },
  { character: "いれる", translation: "to put in", type: "verb" },
  { character: "はしる", translation: "to run", type: "verb" },
  { character: "がんばる", translation: "do one's best", type: "verb" },
  { character: "おくる", translation: "to send", type: "verb" },
  { character: "はらう", translation: "to pay", type: "verb" },
  { character: "つくる", translation: "to make", type: "verb" },
  { character: "まつ", translation: "to wait", type: "verb" },
  { character: "わすれる", translation: "to forget", type: "verb" },
  { character: "びっくりる", translation: "to be surprised", type: "verb" },
  { character: "のんびりる", translation: "to relax", type: "verb" },
  { character: "でんわをします", translation: "to call", type: "verb" },
  { character: "りょうりをします", translation: "to cook", type: "verb" },
  { character: "しごとをします", translation: "to work", type: "verb" },
  { character: "かいものをします", translation: "to shop", type: "verb" },
  { character: "べんきょうをします", translation: "to study", type: "verb" },
  { character: "ふくしゅうをします", translation: "to review", type: "verb" },
  { character: "うんてんをします", translation: "to drive", type: "verb" },
  { character: "します", translation: "to do", type: "verb" },
];

